Set the array component type to "String".
Without this change `(into-array [])` returns an `Object[]` instead of a
`String[]` which is what `.tag` expects, causing:

  java.lang.IllegalArgumentException: No matching method found: tag for class
  opennlp.tools.postag.POSTaggerME